name: Boiler Plate 
on: workflow_dispatch

jobs:
  build:
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: db_name
      DB_HOST: localhost
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      TIMEZONE: Africa/Lagos
      SSLMODE: disable
      USERNAME: postgres
      PASSWORD: password
      DB_NAME: db_name
      MIGRATE: "true"
      IPSTACK_KEY: key
      IPSTACK_BASE_URL: http://api.ipstack.com
      SERVER_PORT: "8019"
      SERVER_SECRET: "mySecretKey"
      SERVER_ACCESSTOKENEXPIREDURATION: "2"
      REQUEST_PER_SECOND: "6"
      TRUSTED_PROXIES: '["192.168.0.1", "192.168.0.2"]'
      EXEMPT_FROM_THROTTLE: '["127.0.0.1", "192.168.0.2", "::1"]'
      APP_NAME: local
      APP_URL: http://localhost:8019
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Run The Project
      run: nohup go run main.go > /dev/null 2>&1 &

    - name: Wait for application to start
      run: sleep 30s

    - name: Reachability
      run: curl http://localhost:8019

    - name: Run All Tests
      run: go test ./... -timeout 99999s